package com.simple.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-730017
 * 2019-03-08T12:38:31.556-07:00
 * Generated source version: 3.2.7.fuse-730017
 *
 */
@WebServiceClient(name = "SimpleWSImplService",
                  wsdlLocation = "http://localhost:9999/ws/hello?wsdl",
                  targetNamespace = "http://ws.simple.com/")
public class SimpleWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.simple.com/", "SimpleWSImplService");
    public final static QName SimpleWSImplPort = new QName("http://ws.simple.com/", "SimpleWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9999/ws/hello?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SimpleWSImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:9999/ws/hello?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SimpleWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SimpleWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SimpleWSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SimpleWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SimpleWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SimpleWS
     */
    @WebEndpoint(name = "SimpleWSImplPort")
    public SimpleWS getSimpleWSImplPort() {
        return super.getPort(SimpleWSImplPort, SimpleWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleWS
     */
    @WebEndpoint(name = "SimpleWSImplPort")
    public SimpleWS getSimpleWSImplPort(WebServiceFeature... features) {
        return super.getPort(SimpleWSImplPort, SimpleWS.class, features);
    }

}
