package com.simple.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-730017
 * 2019-03-26T09:13:14.947-06:00
 * Generated source version: 3.2.7.fuse-730017
 *
 */
@WebService(targetNamespace = "http://ws.simple.com/", name = "SimpleWS")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SimpleWS {

    @WebMethod
    @Action(input = "http://ws.simple.com/SimpleWS/getRandomCityRequest", output = "http://ws.simple.com/SimpleWS/getRandomCityResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.simple.com/", partName = "return")
    public java.lang.String getRandomCity();

    @WebMethod
    @Action(input = "http://ws.simple.com/SimpleWS/getCountryForCityRequest", output = "http://ws.simple.com/SimpleWS/getCountryForCityResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.simple.com/", partName = "return")
    public java.lang.String getCountryForCity(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );
}
