/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This class was generated by running wsd2lrest on the running 
 * wsdl2rest-user-story-ws SOAP service.
 */
package com.simple.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-730017
 * 2019-03-26T09:13:14.947-06:00
 * Generated source version: 3.2.7.fuse-730017
 *
 */
@WebService(targetNamespace = "http://ws.simple.com/", name = "SimpleWS")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SimpleWS {

    @WebMethod
    @Action(input = "http://ws.simple.com/SimpleWS/getRandomCityRequest", output = "http://ws.simple.com/SimpleWS/getRandomCityResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.simple.com/", partName = "return")
    public java.lang.String getRandomCity();

    @WebMethod
    @Action(input = "http://ws.simple.com/SimpleWS/getCountryForCityRequest", output = "http://ws.simple.com/SimpleWS/getCountryForCityResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.simple.com/", partName = "return")
    public java.lang.String getCountryForCity(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );
}
